from datetime import date, datetime as dt
hari_ini=date.today()
now=dt.now()
time=now.strftime("%d %B %Y  %H:%M:%S:%f")
hal_LOGIN="LOGIN TOKOPEDIA".center(40,"=")
hal_HOST="HALAMAN TRANSAKSI".center(40,"=")
hal_HIST="HALAMAN HISTORI".center(40,"=")
print(hal_LOGIN)
email=input("masukkan EMAIL anda  :")
if email.count(" ")>0:quit("Jangan pakai spasi")
password=input("masukkan password anda  :")
login_sukses=f"SELAMAT DATANG {email}, anda masuk pada {time}"
if email=="kukuh11@gmail.com" and password=="12345":print(login_sukses)
elif email!="kukuh11@gmail.com" and password=="12345":quit("email salah????")
elif email=="kukuh11@gmail.com" and password!="12345":quit("email salah????")
else :print("email dan password salah???")
print(hal_HOST)
print("TOKOPEDIA")
print(time)
print("")
print("akun :",email)
print("-------------------------------------")
print("Nama Barang")
print("1.BAJU BATIK LENGAN PENDEK  I Rp.70000")
print("2.BAJU BATIK LENGAN PANJANG I Rp.90000")
print("3.KAOS BATIK KEREN          I Rp.60000")
print("______________________________________")
barang=input("silahkan masukan nama barang :")
harga=int(input("silahkan masukkan harga:"))
jumlah=int(input("silahkan masukkan jumlah:"))
total=harga*jumlah
print("TOTAL   :Rp.",total)
uang=int(input("masukkan nominal  :"))
kembali=uang-total
print("kembali :Rp.",kembali)
print(hal_HIST)
print(email)
print(f"telah membeli barang {barang} sebanyak {jumlah} buah dengan harga Rp.{harga}.dengan total {total}. pada {time}")