from datetime import date, datetime as dt
hari_ini=date.today()
now=dt.now()
time=now.strftime("%d %B %y  %H:%M:%S.%f")
username=input("masukkan username anda :")
if username.count(" ")>0:quit("not spaces")
password=input("masukkan password anda :")
login_sukses=f"selamat datang {username}.anda masuk pada {time}."
if username=="bagas" and password=="12345":print(login_sukses)
elif username!="bagas" and password=="12345":quit("username salah")
elif username=="bagas" and password!="12345":quit("password salah")
else:quit("username and password salah")
print("__________________________")
print("akun :",username)
print("1.topi bloods=Rp.90000")
print("2.topi flanel=Rp.50000")
print("3.topi bucket=Rp.80000")
barang=input("masukkan nama barang :")
jumlah=int(input("masukkan jumlah barang :"))
harga=int(input("masukkan harga barang :"))
total=jumlah*harga
print("total",total)
uang=int(input("masukkan nominal uang :"))
kembali=uang-total
print("kembali",kembali)
print("---------------")
print("akun :",username)
print("tanggal :",time)
print(username)
print(f"telah membeli {barang} sebanyak {jumlah} dengan harga {harga}. dengan total {total}")